-- 羽毛球社团管理平台 - 完整数据库脚本
-- 在 Supabase SQL Editor 中执行此脚本
-- 包含所有表、触发器、约束和 RLS 策略

-- ============================================
-- 第一部分：创建表结构
-- ============================================

-- 用户资料表
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  real_name TEXT NOT NULL,
  student_id TEXT NOT NULL UNIQUE,
  college TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 核心活动表
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'ended')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 分组/队列表
CREATE TABLE IF NOT EXISTS event_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  capacity INT NOT NULL CHECK (capacity > 0),
  claimed INT DEFAULT 0 CHECK (claimed >= 0),
  share_link TEXT,
  checkin_img TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 报名记录表
CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  group_id BIGINT REFERENCES event_groups(id) ON DELETE CASCADE NOT NULL,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, event_id)
);

-- 财务流水表
CREATE TABLE IF NOT EXISTS finance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
  amount DECIMAL(10, 2) NOT NULL CHECK (amount >= 0),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 物资表
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT CHECK (category IN ('fixed_asset', 'consumable')),
  quantity INT DEFAULT 0 CHECK (quantity >= 0),
  unit TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 第二部分：创建索引
-- ============================================

CREATE INDEX IF NOT EXISTS idx_registrations_user_id ON registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_registrations_group_id ON registrations(group_id);
CREATE INDEX IF NOT EXISTS idx_registrations_event_id ON registrations(event_id);
CREATE INDEX IF NOT EXISTS idx_event_groups_event_id ON event_groups(event_id);
CREATE INDEX IF NOT EXISTS idx_profiles_student_id ON profiles(student_id);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);

-- ============================================
-- 第三部分：创建触发器函数
-- ============================================

-- 更新 updated_at 字段
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 并发安全的 claimed 计数更新（关键！）
CREATE OR REPLACE FUNCTION update_group_claimed_safe()
RETURNS TRIGGER AS $$
DECLARE
  current_group RECORD;
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- 使用 FOR UPDATE 锁定行，防止并发问题
    SELECT * INTO current_group 
    FROM event_groups 
    WHERE id = NEW.group_id
    FOR UPDATE;
    
    -- 检查是否已满
    IF current_group.claimed >= current_group.capacity THEN
      RAISE EXCEPTION '该分组名额已满';
    END IF;
    
    -- 更新 claimed 计数
    UPDATE event_groups 
    SET claimed = claimed + 1,
        updated_at = NOW()
    WHERE id = NEW.group_id;
    
    RETURN NEW;
    
  ELSIF TG_OP = 'DELETE' THEN
    -- 删除时减少 claimed
    UPDATE event_groups 
    SET claimed = GREATEST(0, claimed - 1),
        updated_at = NOW()
    WHERE id = OLD.group_id;
    
    RETURN OLD;
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 自动创建用户资料（注册时）
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, real_name, student_id, college, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'real_name', '待补充'),
    COALESCE(NEW.raw_user_meta_data->>'student_id', 'TEMP_' || NEW.id::TEXT),
    COALESCE(NEW.raw_user_meta_data->>'college', '待补充'),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 第四部分：创建触发器
-- ============================================

-- updated_at 触发器
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at 
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_events_updated_at ON events;
CREATE TRIGGER update_events_updated_at 
  BEFORE UPDATE ON events
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_event_groups_updated_at ON event_groups;
CREATE TRIGGER update_event_groups_updated_at 
  BEFORE UPDATE ON event_groups
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_inventory_updated_at ON inventory;
CREATE TRIGGER update_inventory_updated_at 
  BEFORE UPDATE ON inventory
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- claimed 计数触发器（关键！）
DROP TRIGGER IF EXISTS update_claimed_on_registration ON registrations;
CREATE TRIGGER update_claimed_on_registration
  BEFORE INSERT OR DELETE ON registrations
  FOR EACH ROW EXECUTE FUNCTION update_group_claimed_safe();

-- 自动创建用户资料触发器
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================
-- 第五部分：添加数据完整性约束
-- ============================================

-- 确保 claimed 不会超过 capacity
ALTER TABLE event_groups 
DROP CONSTRAINT IF EXISTS check_claimed_capacity;
ALTER TABLE event_groups 
ADD CONSTRAINT check_claimed_capacity 
CHECK (claimed <= capacity);

-- ============================================
-- 第六部分：启用 RLS
-- ============================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE finance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 第七部分：删除旧策略
-- ============================================

DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
DROP POLICY IF EXISTS "Anyone can view open events" ON events;
DROP POLICY IF EXISTS "Anyone can view event groups" ON event_groups;
DROP POLICY IF EXISTS "Users can view own registrations" ON registrations;
DROP POLICY IF EXISTS "Users can insert own registrations" ON registrations;
DROP POLICY IF EXISTS "Users can delete own registrations" ON registrations;
DROP POLICY IF EXISTS "Anyone can view finance records" ON finance_records;
DROP POLICY IF EXISTS "Anyone can view inventory" ON inventory;

-- ============================================
-- 第八部分：创建 RLS 策略
-- ============================================

-- Profiles 表策略
CREATE POLICY "Users can view own profile" 
  ON profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
  ON profiles FOR UPDATE 
  USING (auth.uid() = id);

-- Events 表策略
CREATE POLICY "Anyone can view open events" 
  ON events FOR SELECT 
  USING (status = 'open');

-- Event Groups 表策略
CREATE POLICY "Anyone can view event groups" 
  ON event_groups FOR SELECT 
  USING (true);

-- Registrations 表策略
CREATE POLICY "Users can view own registrations" 
  ON registrations FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own registrations" 
  ON registrations FOR DELETE 
  USING (auth.uid() = user_id);

-- Finance Records 表策略
CREATE POLICY "Anyone can view finance records" 
  ON finance_records FOR SELECT 
  USING (true);

-- Inventory 表策略
CREATE POLICY "Anyone can view inventory" 
  ON inventory FOR SELECT 
  USING (true);

-- ============================================
-- 第九部分：插入示例数据
-- ============================================

INSERT INTO events (title, description, status) 
VALUES 
  ('周末羽毛球活动', '本周末羽毛球活动，欢迎新老成员参加！', 'open'),
  ('月度友谊赛', '社团内部友谊赛，分组对抗', 'open')
ON CONFLICT DO NOTHING;

INSERT INTO event_groups (event_id, name, capacity, share_link, checkin_img)
SELECT 
  e.id, '新手场', 7,
  'https://example.com/share/newbie',
  'https://via.placeholder.com/300?text=新手场签到码'
FROM events e WHERE e.title = '周末羽毛球活动' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO event_groups (event_id, name, capacity, share_link, checkin_img)
SELECT 
  e.id, '高手场', 7,
  'https://example.com/share/expert',
  'https://via.placeholder.com/300?text=高手场签到码'
FROM events e WHERE e.title = '周末羽毛球活动' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO finance_records (type, amount, description)
VALUES
  ('income', 500.00, '会费收入'),
  ('expense', 200.00, '场地租金'),
  ('expense', 150.00, '羽毛球购买')
ON CONFLICT DO NOTHING;

INSERT INTO inventory (name, category, quantity, unit, description)
VALUES
  ('羽毛球', 'consumable', 50, '个', 'YONEX 比赛用球'),
  ('球拍', 'fixed_asset', 10, '支', '社团公用球拍'),
  ('球网', 'fixed_asset', 2, '套', '比赛用球网')
ON CONFLICT DO NOTHING;

-- ============================================
-- 完成！
-- ============================================